require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe Admin::AnswersController do
  render_views

  let(:question) { Factory :question }
  let(:answer) { Factory :answer, :question => question }
  let(:user) { Factory :user }

  before do
    sign_in user
    Input.stubs(:available_inputs).returns({1 => :foo})
  end

  describe "GET show" do
    it "assigns the requested answer as @answer" do
      get :show, :id => answer.id
      assigns(:answer).should == answer
      response.should be_success
    end
  end

  describe "GET edit" do
    it "assigns the requested answer as @answer" do
      get :edit, :id => answer.id
      assigns(:answer).should == answer
      response.should render_template('edit')
    end
  end

  describe "PUT update" do
    before do
      @question = Factory :question
      @answer = @question.answers.first
    end

    describe "with valid params" do
      it "updates the requested answer" do
        put :update, :id => @answer.id, :answer => { :text_nl => 'Hi!'}
        assigns(:answer).should == @answer
        @answer.reload.text_nl.should == 'Hi!'
        response.should redirect_to(admin_question_url(@question))
      end
    end

    describe "with valid params and a conflict" do
      it "updates the requested answer" do
        a1 = Factory :answer
        a2 = Factory :answer
        @answer.conflicting_answer_ids = [a1.id]
        @answer.save

        @answer.reload.conflicting_answer_ids.should == [a1.id]

        put :update, :id => @answer.id, :answer => { :text_nl => 'Hi!', :conflicting_answer_ids => [a2.id]}
        assigns(:answer).should == @answer
        @answer.reload.text_nl.should == 'Hi!'
        @answer.reload.conflicting_answer_ids.should == [a2.id]

        response.should redirect_to(admin_question_url(@question))
      end
    end

    describe "with invalid params" do
      it "assigns the answer as @answer" do
        put :update, :id => @answer.id, :answer => { :text_nl => '' }
        assigns(:answer).should == @answer
        response.should render_template('edit')
      end
    end
  end

  describe "DELETE destroy" do
    it "should delete an answer" do
      @question = Factory :question
      @answer = @question.answers.first
      lambda {
        delete :destroy, :id => @answer.id
      }.should change(Answer, :count)
      response.should redirect_to(admin_question_path(@question))
    end
  end
end
