development: &DEV
  hostname: "localhost:3000"
  # api_base_path:      "http://localhost:3001/api/v1/api_scenarios/"
  # view_scenario_path: "http://localhost:3001/scenarios/"
  api_base_path:      "http://staging.et-model.com/api/v1/api_scenarios/"
  view_scenario_path: "http://staging.et-model.com/scenarios/"
  api_session_settings:
    :country: 'nl'
    :end_year: 2025
  
test:
  <<: *DEV
production:
  <<: *DEV
  hostname: "mixer.et-model.com"
  api_base_path:      "http://staging.et-model.com/api/v1/api_scenarios/"
  view_scenario_path: "http://staging.et-model.com/scenarios/"
