development: &DEV
  api_base_path: "http://testing.et-model.com/api/v1/api_scenarios/"
  api_session_settings:
    :country: '"nl"'  # HACK because this is passed to #options_for_javascript
    :end_year: 2025
  
test:
  <<: *DEV
production:
  <<: *DEV