require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AnswersController do
  render_views
  
  let(:answer) { Factory :answer }

  describe "GET show" do
    it "assigns the requested answer as @answer" do
      get :show, :id => answer.id
      assigns(:answer).should be(answer)
      response.should be_success
    end
  end

  describe "GET edit" do
    it "assigns the requested answer as @answer" do
      get :edit, :id => answer.id
      assigns(:answer).should be(answer)
      response.should be_success
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested answer" do
        answer.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => answer.id, :answer => {'these' => 'params'}
      end

      it "assigns the requested answer as @answer" do
        put :update, :id => "1"
        assigns(:answer).should be(answer)
      end

      it "redirects to the answer" do
        put :update, :id => "1"
        response.should redirect_to(answer_url(answer))
      end
    end

    describe "with invalid params" do
      it "assigns the answer as @answer" do
        put :update, :id => "1"
        assigns(:answer).should be(answer)
      end

      it "re-renders the 'edit' template" do        Answer.stub(:find) { answer(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end
end
