require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe InputsController do

  def mock_input(stubs={})
    @mock_input ||= mock_model(Input, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all inputs as @inputs" do
      Input.stub(:all) { [mock_input] }
      get :index
      assigns(:inputs).should eq([mock_input])
    end
  end

  describe "GET show" do
    it "assigns the requested input as @input" do
      Input.stub(:find).with("37") { mock_input }
      get :show, :id => "37"
      assigns(:input).should be(mock_input)
    end
  end

  describe "GET new" do
    it "assigns a new input as @input" do
      Input.stub(:new) { mock_input }
      get :new
      assigns(:input).should be(mock_input)
    end
  end

  describe "GET edit" do
    it "assigns the requested input as @input" do
      Input.stub(:find).with("37") { mock_input }
      get :edit, :id => "37"
      assigns(:input).should be(mock_input)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created input as @input" do
        Input.stub(:new).with({'these' => 'params'}) { mock_input(:save => true) }
        post :create, :input => {'these' => 'params'}
        assigns(:input).should be(mock_input)
      end

      it "redirects to the created input" do
        Input.stub(:new) { mock_input(:save => true) }
        post :create, :input => {}
        response.should redirect_to(input_url(mock_input))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved input as @input" do
        Input.stub(:new).with({'these' => 'params'}) { mock_input(:save => false) }
        post :create, :input => {'these' => 'params'}
        assigns(:input).should be(mock_input)
      end

      it "re-renders the 'new' template" do
        Input.stub(:new) { mock_input(:save => false) }
        post :create, :input => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested input" do
        Input.stub(:find).with("37") { mock_input }
        mock_input.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :input => {'these' => 'params'}
      end

      it "assigns the requested input as @input" do
        Input.stub(:find) { mock_input(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:input).should be(mock_input)
      end

      it "redirects to the input" do
        Input.stub(:find) { mock_input(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(input_url(mock_input))
      end
    end

    describe "with invalid params" do
      it "assigns the input as @input" do
        Input.stub(:find) { mock_input(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:input).should be(mock_input)
      end

      it "re-renders the 'edit' template" do
        Input.stub(:find) { mock_input(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested input" do
      Input.stub(:find).with("37") { mock_input }
      mock_input.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the inputs list" do
      Input.stub(:find) { mock_input }
      delete :destroy, :id => "1"
      response.should redirect_to(inputs_url)
    end
  end

end
